services:
  dev:
    container_name: fourvenues-api_dev
    image: fourvenues-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:4.2
    container_name: mongo-service
    ports:
      - 27017:27017
    env_file: ./src/config/environments/.env.development
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file: ./src/config/environments/.env.development
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-service

volumes:
  mongodb:
